//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace feedme_backend
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ID { get; set; }
        public int UserFK { get; set; }
        public int RestaurantFK { get; set; }
        public int Stars { get; set; }
        public string Comments { get; set; }
        public System.DateTime Timestamp { get; set; }
        public int OrderFK { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual User User { get; set; }
        public virtual Order Order { get; set; }
    }
}
